name: CI/CD
on:
  pull_request:
    branches: ["main"]
  push: 
    branches: ["*"]
jobs:
  build:
    strategy:
      matrix: 
        os: [ubuntu-latest,windows-latest,macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - run: pnpm install
      - run: pnpm tauri build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-nextest
      - run: |
          cd src-tauri
          cargo nextest run