name: CI/CD
on:
  pull_request:
    branches: ["main"]
  push: 
    branches: ["*"]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest,windows-latest,macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ./src-tauri/target
            ~/.cargo
          key: ${{runner.os}}-${{hashFiles('**/Cargo.lock')}}
          restore-keys: ${{runner.os}}-
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm tauri build
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ./src-tauri/target
            ~/.cargo
          key: ${{runner.os}}-${{hashFiles('**/Cargo.lock')}}
          restore-keys: ${{runner.os}}-
      - uses: taiki-e/install-action@cargo-nextest
      - run: |
          cd src-tauri
          cargo nextest run